### ISSUE TITLE
[Feature request] Automatically change profile picture

### ISSUE THREAD

**Issue by RedHazardTwelve** [kurd/pyxenforo#1]
Hello, I love your API, could you please add a way to change a profile picture automatically (picture from link or directly from pc)?

I'd really love to see that feature!

**Comment by kurd** [comment]
I'll look into it this weekend.

**Comment by RedHazardTwelve** [comment]
great, I can't wait! 😸

**Comment by kurd** [comment]
Method `avatar` implemented, see the docstrings for documentation until proper docs are released.
